/* This file has been generated by parse-gir.py, do not hand edit */
using System;
using System.Runtime.InteropServices;

namespace Cogl
{
    public partial class Context
    {
        [DllImport("cogl2.dll")]
        public static extern IntPtr cogl_context_get_display(IntPtr o);

        public Display GetDisplay()
        {
            IntPtr p = cogl_context_get_display(handle);
            return new Display(p);
        }

    }
}
