/* This file has been generated by parse-gir.py, do not hand edit */
using System;
using System.Runtime.InteropServices;

namespace Cogl
{
    public partial class OnScreenTemplate
    {
        [DllImport("cogl2.dll")]
        public static extern void cogl_onscreen_template_set_samples_per_pixel(IntPtr o, int n);

        public void SetSamplesPerPixel(int n)
        {
            cogl_onscreen_template_set_samples_per_pixel(handle, n);
        }

        [DllImport("cogl2.dll")]
        public static extern void cogl_onscreen_template_set_swap_throttled(IntPtr o, bool throttled);

        public void SetSwapThrottled(bool throttled)
        {
            cogl_onscreen_template_set_swap_throttled(handle, throttled);
        }

    }
}
