/* This file has been generated by parse-gir.py, do not hand edit */
using System;
using System.Runtime.InteropServices;

namespace Cogl
{
    public partial class SwapChain
    {
        [DllImport("cogl2.dll")]
        public static extern void cogl_swap_chain_set_has_alpha(IntPtr o, bool has_alpha);

        public void SetHasAlpha(bool has_alpha)
        {
            cogl_swap_chain_set_has_alpha(handle, has_alpha);
        }

        [DllImport("cogl2.dll")]
        public static extern void cogl_swap_chain_set_length(IntPtr o, int length);

        public void SetLength(int length)
        {
            cogl_swap_chain_set_length(handle, length);
        }

    }
}
