/* This file has been generated by parse-gir.py, do not hand edit */
using System;
using System.Runtime.InteropServices;

namespace Cogl
{
    public partial class Texture
    {
        [DllImport("cogl2.dll")]
        public static extern PixelFormat cogl_texture_get_format(IntPtr o);

        public PixelFormat GetFormat()
        {
            return cogl_texture_get_format(handle);
        }

        [DllImport("cogl2.dll")]
        public static extern bool cogl_texture_get_gl_texture(IntPtr o);

        public bool GetGlTexture()
        {
            return cogl_texture_get_gl_texture(handle);
        }

        [DllImport("cogl2.dll")]
        public static extern uint cogl_texture_get_height(IntPtr o);

        public uint GetHeight()
        {
            return cogl_texture_get_height(handle);
        }

        [DllImport("cogl2.dll")]
        public static extern int cogl_texture_get_max_waste(IntPtr o);

        public int GetMaxWaste()
        {
            return cogl_texture_get_max_waste(handle);
        }

        [DllImport("cogl2.dll")]
        public static extern uint cogl_texture_get_width(IntPtr o);

        public uint GetWidth()
        {
            return cogl_texture_get_width(handle);
        }

        [DllImport("cogl2.dll")]
        public static extern bool cogl_texture_is_sliced(IntPtr o);

        public bool IsSliced()
        {
            return cogl_texture_is_sliced(handle);
        }

    }
}
