/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    [Flags]
    public enum BufferBit
    {
        Color = 1,
        Depth = 2,
        Stencil = 4
    }
}
