/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    [Flags]
    public enum ColorMask
    {
        None = 0,
        Red = 1,
        Green = 2,
        Blue = 4,
        Alpha = 8,
        All = 15
    }
}
