/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum Driver
    {
        Any = 0,
        Nop = 1,
        Gl = 2,
        Gl3 = 3,
        Gles1 = 4,
        Gles2 = 5
    }
}
