/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum PipelineWrapMode
    {
        Repeat = 10497,
        MirroredRepeat = 33648,
        ClampToEdge = 33071,
        Automatic = 519
    }
}
