/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum PipelineAlphaFunc
    {
        Never = 512,
        Less = 513,
        Equal = 514,
        Lequal = 515,
        Greater = 516,
        Notequal = 517,
        Gequal = 518,
        Always = 519
    }
}
