/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum PipelineCullFaceMode
    {
        None = 0,
        Front = 1,
        Back = 2,
        Both = 3
    }
}
