/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum PipelineFilter
    {
        Nearest = 9728,
        Linear = 9729,
        NearestMipmapNearest = 9984,
        LinearMipmapNearest = 9985,
        NearestMipmapLinear = 9986,
        LinearMipmapLinear = 9987
    }
}
