/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum PixelFormat
    {
        Any = 0,
        A_8 = 65,
        RGB_565 = 34,
        RGBA_4444 = 98,
        RGBA_4444_PRE = 610,
        RGBA_5551 = 16777314,
        RGBA_5551_PRE = 16777826,
        G_8 = 1,
        RGB_888 = 3,
        BGR_888 = 131,
        RGBA_8888 = 68,
        BGRA_8888 = 196,
        ARGB_8888 = 324,
        ABGR_8888 = 452,
        RGBA_8888_PRE = 580,
        BGRA_8888_PRE = 708,
        ARGB_8888_PRE = 836,
        ABGR_8888_PRE = 964,
        RGBA_1010102 = 33554500,
        BGRA_1010102 = 33554628,
        ARGB_2101010 = 33554756,
        ABGR_2101010 = 33554884,
        RGBA_1010102_PRE = 33555012,
        BGRA_1010102_PRE = 33555140,
        ARGB_2101010_PRE = 33555268,
        ABGR_2101010_PRE = 33555396,
        DEPTH_16 = 1026,
        DEPTH_32 = 1028,
        DEPTH_24_STENCIL_8 = 3076
    }
}
