/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    [Flags]
    public enum RendererConstraint
    {
        UsesX11 = 1,
        UsesXlib = 2,
        UsesEgl = 4,
        SupportsCoglGles2 = 8
    }
}
