/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum TextureType
    {
        Texture2D = 0,
        Texture3D = 1,
        TextureRectangle = 2
    }
}
