/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    [Flags]
    public enum TextureFlags
    {
        None = 0,
        NoAutoMipmap = 1,
        NoSlicing = 2,
        NoAtlas = 4
    }
}
