/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum VerticesMode
    {
        Points = 0,
        Lines = 1,
        LineLoop = 2,
        LineStrip = 3,
        Triangles = 4,
        TriangleStrip = 5,
        TriangleFan = 6
    }
}
