/* This file has been generated by parse-gir.py, do not hand edit */
using System;

namespace Cogl
{
    public enum WinsysID
    {
        Any = 0,
        Stub = 1,
        Glx = 2,
        EglXlib = 3,
        EglNull = 4,
        EglGdl = 5,
        EglWayland = 6,
        EglKms = 7,
        EglAndroid = 8,
        Wgl = 9,
        Sdl = 10
    }
}
